### ISSUE TITLE
How to edit the YAML?

### ISSUE THREAD

**Issue by pdhixenbaugh** [geerlingguy/pi-timelapse#27]
I'm trying to specify a resolution and a white balance, however whenever I try to do something other than the default ` { } `, the program throws an exception. What is the proper way to modify the .yml so that it uses the individual values for resolution or for white balance?

**Comment by shantigilbert** [comment]
For resolution: 
`resolution: { width: 1920, height: 1440 }`

for white balance: 
`white_balance: { red_gain: 1.3, blue_gain: 1.75 }`

**Comment by geerlingguy** [comment]
Alternatively:

```yaml
resolution:
  width: 1920
  height: 1440

white_balance:
  red_gain: 1.3
  blue_gain: 1.75
```
